version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    driver: bridge